version: "3"
services:
  app:
    container_name: my-wallet-app
    build: .
    environment:
      - API_HOST
      - API_PORT
      - MONGO_HOST=mongodb://mongo
      - MONGO_PORT
      - JWT_SECRET
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - mongo
  mongo:
    container_name: my-wallet-db
    image: mongo:6.0.5
    environment:
      - MONGO_PORT
    command: mongod --port ${MONGO_PORT}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    restart: always
    volumes:
      - ./data:/data/db
