version: "3"
services:
  app:
    container_name: my-wallet-app
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27018
    depends_on:
      - mongo
  mongo:
    container_name: my-wallet-db
    image: mongo:6.0.5
    command: mongod --port 27018
    ports:
      - "27018:27018"
    volumes:
      - ./data:/data/db
