version: "3"
services:
  app:
    container_name: my-wallet-app
    build: .
    environment:
      - API_HOST
      - API_PORT
      - MONGO_URI=mongodb://mongo
      - JWT_SECRET
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - mongo
  mongo:
    container_name: my-wallet-db
    image: mongo:6.0.5
    restart: always
    volumes:
      - ./data:/data/db
